

export const APPLIST_INITILIZE = 'APPLIST_INITILIZE'
export const APPLIST_FETCH_START = 'APPLIST_FETCH_START'
export const APPLIST_FETCH_REQUEST = 'APPLIST_FETCH_REQUEST'
export const APPLIST_FETCH_SUCCESS = 'APPLIST_FETCH_SUCCESS'
export const APPLIST_FETCH_FAIL = 'APPLIST_FETCH_FAIL'

export const APPLIST_APP_ADD_START = 'APPLIST_APP_ADD_START'
export const APPLIST_APP_ADD_SUCCESS = 'APPLIST_APP_ADD_SUCCESS'
export const APPLIST_APP_ADD_FAIL = 'APPLIST_APP_ADD_FAIL'

export const APPLIST_APP_REMOVE_START = 'APPLIST_APP_REMOVE_START'
export const APPLIST_APP_REMOVE_SUCCESS = 'APPLIST_APP_REMOVE_SUCCESS'
export const APPLIST_APP_REMOVE_FAIL = 'APPLIST_APP_REMOVE_FAIL'

export const initializeAppList = () => (
    {
        type: APPLIST_INITILIZE
    })