

export const CONNECTIONLIST_INITILIZE = 'CONNECTIONLIST_INITILIZE'
export const CONNECTIONLIST_FETCH_START = 'CONNECTIONLIST_FETCH_START'
export const CONNECTIONLIST_FETCH_REQUEST = 'CONNECTIONLIST_FETCH_REQUEST'
export const CONNECTIONLIST_FETCH_SUCCESS = 'CONNECTIONLIST_FETCH_SUCCESS'
export const CONNECTIONLIST_FETCH_FAIL = 'CONNECTIONLIST_FETCH_FAIL'

export const CONNECTIONLIST_CONNECTION_CREATE_START = 'CONNECTIONLIST_CONNECTION_CREATE_START'
export const CONNECTIONLIST_CONNECTION_CREATE_SUCCESS = 'CONNECTIONLIST_CONNECTION_CREATE_SUCCESS'
export const CONNECTIONLIST_CONNECTION_CREATE_FAIL = 'CONNECTIONLIST_CONNECTION_CREATE_FAIL'

export const CONNECTIONLIST_CONNECTION_DELETE_START = 'CONNECTIONLIST_CONNECTION_DELETE_START'
export const CONNECTIONLIST_CONNECTION_DELETE_SUCCESS = 'CONNECTIONLIST_CONNECTION_DELETE_SUCCESS'
export const CONNECTIONLIST_CONNECTION_DELETE_FAIL = 'CONNECTIONLIST_CONNECTION_DELETE_FAIL'



export const initializeConnectionList = (appId) => (
    {
        type: CONNECTIONLIST_INITILIZE,
        appId: appId
    })